# ローカル開発環境用
version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-medicine-diary
    environment:
      MYSQL_DATABASE: 'medicine_diary'
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
      TZ: 'Asia/Tokyo'
    ports:
      - '13306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
  minio:
    image: minio/minio:RELEASE.2023-09-30T07-02-29Z
    container_name: minio-medicine_diary
    environment:
      MINIO_ROOT_USER: 'root'
      MINIO_ROOT_PASSWORD: 'root-password'
    ports:
      - '19000:9000'
      - '19090:9090' # コンソール用のポート
    volumes:
      - minio-data:/data
    command: ['server', '/data', '--console-address', ':9090']
  createbuckets:
    image: minio/mc:RELEASE.2023-09-29T16-41-22Z
    container_name: createbuckets-medicine-diary
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      mc alias set myminio http://minio:9000 root root-password;
      mc mb --ignore-existing myminio/medicine-diary;
      mc anonymous set download myminio/medicine-diary;
      exit 0;"
  springboot:
    container_name: springboot-medicine-diary
    image: openjdk:17-jdk-slim-bullseye
    depends_on:
      - mysql
      - minio
    ports:
      - '8080:8080'
      - '5005:5005' # デバッグ用のポート
    volumes:
      - .:/project
    working_dir: /project
    environment:
      GOOGLE_OAUTH2_CLIENT_ID: ${GOOGLE_OAUTH2_CLIENT_ID}
      GOOGLE_OAUTH2_CLIENT_SECRET: ${GOOGLE_OAUTH2_CLIENT_SECRET}
      MYSQL_PORT: '13306'
      MYSQL_PASSWORD: 'root'
    command: ./gradlew bootRun -Pprofiles=dev

volumes:
  mysql-data:
  minio-data: