# 開発環境用
version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-medicine-diary
    environment:
      MYSQL_DATABASE: 'medicine_diary'
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
      TZ: 'Asia/Tokyo'
    ports:
      - '13306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
  minio:
    image: minio/minio:RELEASE.2023-09-30T07-02-29Z
    container_name: minio-medicine-diary
    environment:
      MINIO_ROOT_USER: 'root'
      MINIO_ROOT_PASSWORD: 'root-password'
    ports:
      - '19000:9000'
      - '19090:9090' # 管理ダッシュボード用
    volumes:
      - minio-data:/data
    command: ['server', '/data', '--console-address', ':9090']
  createbuckets:
    image: minio/mc:RELEASE.2023-09-29T16-41-22Z
    container_name: createbuckets-medicine-diary
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      mc alias set myminio http://minio:9000 root root-password;
      mc mb --ignore-existing myminio/medicine-diary;
      mc anonymous set download myminio/medicine-diary;
      exit 0;"
  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog-medicine-diary
    ports:
      - '11025:1025'
      - '18025:8025' # 管理ダッシュボード用
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    container_name: keycloak-medicine-diary
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - '28080:8080' # 管理ダッシュボード用
    volumes:
      - ./docker/keycloak/data/import:/opt/keycloak/data/import
    command: start-dev  --import-realm # 開発モードで起動
  app:
    image: openjdk:17-jdk-slim-bullseye
    container_name: app-medicine-diary
    depends_on:
      - mysql
      - minio
      - mailhog
      - keycloak
    ports:
      - '18080:8080'
    tty: true
    volumes:
      - .:/project
    working_dir: /project

volumes:
  mysql-data:
  minio-data:
  mailhog-data:
