# ローカル開発環境用
version: '3.8'

services:
  springboot:
    container_name: springboot-medicine-diary
    image: openjdk:17-jdk-slim-bullseye
    ports:
      - '8080:8080'
      - '5005:5005' # デバッグ用のポート
    volumes:
      - .:/project
    working_dir: /project
    environment:
      GOOGLE_OAUTH2_CLIENT_ID: ${GOOGLE_OAUTH2_CLIENT_ID}
      GOOGLE_OAUTH2_CLIENT_SECRET: ${GOOGLE_OAUTH2_CLIENT_SECRET}
    command: ./gradlew bootRun -Pprofiles=dev