# 開発環境用

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${devEnv.servers.mysql.host}:${devEnv.servers.mysql.port}/medicine_diary
    username: root
    password: root
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}
            redirectUri: http://${devEnv.servers.app.host}:${devEnv.servers.app.port}/login/oauth2/code/github
          line:
            clientId: ${LINE_CLIENT_ID}
            clientSecret: ${LINE_CLIENT_SECRET}
            provider: line
            scope: profile
            authorizationGrantType: authorization_code
            redirectUri: http://${devEnv.servers.app.host}:${devEnv.servers.app.port}/login/oauth2/code/line
          yahoo:
            clientId: ${YAHOO_CLIENT_ID}
            clientSecret: ${YAHOO_CLIENT_SECRET}
            provider: yahoo
            scope: openid
            authorizationGrantType: authorization_code
            redirectUri: http://${devEnv.servers.app.host}:${devEnv.servers.app.port}/login/oauth2/code/yahoo
        provider:
          line:
            authorizationUri: https://access.line.me/oauth2/v2.1/authorize
            tokenUri: https://api.line.me/oauth2/v2.1/token
            userInfoUri: https://api.line.me/v2/profile
            userNameAttribute: userId
          yahoo:
            authorizationUri: https://auth.login.yahoo.co.jp/yconnect/v2/authorization
            tokenUri: https://auth.login.yahoo.co.jp/yconnect/v2/token
            jwkSetUri: https://auth.login.yahoo.co.jp/yconnect/v2/jwks
  mail:
    host: ${devEnv.servers.minio.host}
    port: ${devEnv.servers.minio.port}
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000


# Actuatorエンドポイントへのアクセス制御
management:
  endpoint:
    env:
      showValues: always
    health:
      showDetails: always
  endpoints:
    web:
      basePath: /actuator
      exposure:
        include: '*'
  metrics:
    web:
      server:
        requestsMetricName: http.server.requests
    distribution:
      percentiles:
        http.server.requests: 0.5, 0.99

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.springframework.web: DEBUG
    sql: DEBUG
    example.configuration.logging.TraceLoggingInterceptor: TRACE



application:
  name: お薬日記
  endpoint:
    web: http://${devEnv.servers.app.host}:${devEnv.servers.app.port}
    image: http://${devEnv.servers.minio.host}:${devEnv.servers.minio.port}/medicine-diary
  emailAddress: application@example.co.jp
  admin:
    username: admin
    password: password

infrastructure:
  storage:
    minio:
      user: root
      password: root-password
      endpoint: http://${devEnv.servers.minio.host}:${devEnv.servers.minio.port}
      bucketName: progress-management