spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://host.docker.internal:13306/medicine_diary
    username: root
    password: root
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}
          line:
            clientId: ${LINE_CLIENT_ID}
            clientSecret: ${LINE_CLIENT_SECRET}
            provider: line
            scope: profile
            authorizationGrantType: authorization_code
            redirectUri: http://localhost:8080/login/oauth2/code/line
          yahoo:
            clientId: ${YAHOO_CLIENT_ID}
            clientSecret: ${YAHOO_CLIENT_SECRET}
            provider: yahoo
            scope: openid
            authorizationGrantType: authorization_code
            redirectUri: http://localhost:8080/login/oauth2/code/yahoo
        provider:
          line:
            authorizationUri: https://access.line.me/oauth2/v2.1/authorize
            tokenUri: https://api.line.me/oauth2/v2.1/token
            userInfoUri: https://api.line.me/v2/profile
            userNameAttribute: userId
          yahoo:
            authorizationUri: https://auth.login.yahoo.co.jp/yconnect/v2/authorization
            tokenUri: https://auth.login.yahoo.co.jp/yconnect/v2/token
            jwkSetUri: https://auth.login.yahoo.co.jp/yconnect/v2/jwks
  mail:
    host: host.docker.internal
    port: 11025
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000


# Actuatorエンドポイントへのアクセス制御
management:
  endpoint:
    env:
      show-values: always
    health:
      show-details: always
  endpoints:
    web:
      basePath: /actuator
      exposure:
        include: '*'
  metrics:
    web:
      server:
        requests-metric-name: http.server.requests
    distribution:
      percentiles:
        http.server.requests: 0.5, 0.99

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.springframework.web.servlet: INFO
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.datasource.DataSourceTransactionManager: DEBUG
    example: DEBUG
    example.presentation.shared.logging.HttpSessionEventLoggingListener: DEBUG
    example.presentation.shared.logging.TraceLoggingInterceptor: TRACE
    example.presentation.shared.logging.ExceptionLoggingFilter: INFO

minio:
  user: root
  password: root-password
  endpoint: http://host.docker.internal:19000
  bucketName: medicine-diary


application:
  name: お薬日記
  endpoint:
    web: http://localhost:8080
    image: http://host.docker.internal:19000/medicine-diary
  admin:
    username: admin
    password: password
    emailAddress: application@example.co.jp