spring:
  datasource:
    driverClassName: 'com.mysql.cj.jdbc.Driver'
    url: 'jdbc:mysql://host.docker.internal:13306/medicine_diary'
    username: 'root'
    password: 'root'

minio:
  user: 'root'
  password: 'root-password'
  endpoint: 'http://host.docker.internal:19000'
  bucketName: 'medicine-diary'