spring:
  profiles:
    active: ${PROFILES:local}
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: '${GOOGLE_OAUTH2_CLIENT_ID}'
            clientSecret: '${GOOGLE_OAUTH2_CLIENT_SECRET}'
  # TODO: flyway を利用するように変更する
  sql:
    init:
      mode: always
      encoding: utf-8

mybatis:
  typeAliasesPackage: 'example.domain' # XML の中でクラスを指定する際、完全修飾名の記述を省略できるようにする