spring:
  profiles:
    active: ${PROFILES:local}
  servlet:
    multipart:
      maxFileSize: 512000 # アップロードを許可する1ファイルの最大バイト数 500KB
      maxRequestSize: 614400 # multipart/form-data リクエストの Content-Length の最大値 600KB
      fileSizeThreshold: 0 # アップロードされたファイルの中身を、一時ファイルとして保存するかの閾値
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: '${GOOGLE_OAUTH2_CLIENT_ID}'
            clientSecret: '${GOOGLE_OAUTH2_CLIENT_SECRET}'
          github:
            clientId: '${GITHUB_CLIENT_ID}'
            clientSecret: '${GITHUB_CLIENT_SECRET}'
          line:
            clientId: '${LINE_CLIENT_ID}'
            clientSecret: '${LINE_CLIENT_SECRET}'
            provider: 'line'
            scope: 'profile'
            authorizationGrantType: 'authorization_code'
            redirectUri: 'http://localhost:8080/login/oauth2/code/line'
        provider:
          line:
            authorizationUri: 'https://access.line.me/oauth2/v2.1/authorize'
            tokenUri: 'https://api.line.me/oauth2/v2.1/token'
            userInfoUri: 'https://api.line.me/v2/profile'
            userNameAttribute: 'userId'
  sql:
    init:
      mode: always
      encoding: utf-8

mybatis:
  typeAliasesPackage: 'example.domain' # XML の中でクラスを指定する際、完全修飾名の記述を省略できるようにする