version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1
  aws-ecs: circleci/aws-ecs@3.2.0

jobs:
  test-app:
    machine:
      image: ubuntu-2204:2023.10.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          command: |
            docker compose up --build -d
            docker compose exec -T app bash -c "chmod +x ./gradlew && ./gradlew test"
  build-app:
    docker:
      - image: cimg/openjdk:17.0.8
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          command: |
            chmod +x ./gradlew
            ./gradlew test
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .
  build-and-push-image:
    docker:
      - image: cimg/base:2023.09
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: ~/repo
      - aws-ecr/build-and-push-image:
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          tag: "${CIRCLE_SHA1}"
          path: ~/repo
          build-path: ~/repo

workflows:
  version: 2.1
  test-build:
    jobs:
      - test-app
      - build-app:
          requires:
            - test-app
          filters:
            branches:
              only:
                - main
      - build-and-push-image:
          requires:
            - build-app
          filters:
            branches:
              only:
                - main
      - aws-ecs/deploy-service-update:
          requires:
            - build-and-push-image
          family: "${AWS_RESOURCE_NAME_PREFIX}-service"
          cluster: "${AWS_RESOURCE_NAME_PREFIX}-cluster"
          container-image-name-updates: "container=springboot, image-and-tag=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWS_RESOURCE_NAME_PREFIX}:${CIRCLE_SHA1}"
          filters:
            branches:
              only:
                - main