version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1

jobs:
  test-app:
    docker:
      - image: cimg/openjdk:17.0.8
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            - v1-dependencies-
      - run: chmod +x ./gradlew
      - run: ./gradlew test
      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}
  build-app:
    docker:
      - image: cimg/openjdk:17.0.8
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            - v1-dependencies-
      - run: chmod +x ./gradlew
      - run: ./gradlew bootJar
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .
  build-and-push-image:
    docker:
      - image: cimg/base:2023.09
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: ~/repo
      - aws-ecr/build-and-push-image:
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          tag: "${CIRCLE_SHA1}"
          path: ~/repo
          build-path: ~/repo

workflows:
  version: 2.1
  test-build:
    jobs:
      - test-app
      - build-app:
          requires:
            - test-app
      - build-and-push-image:
          requires:
            - build-app